numero1 = float(input("Digite o primeiro numero: "))
numero2 = float(input("Digite o segundo numero: "))
numero_Real = float(input("Digite o numero Real: "))
retorna1 = numero1 * 2 *(numero2 / 2)          
print ("O produto do dobro do primeiro com metade do segundo =", retorna1  )
retorna2 = (numero1 * 3) + numero_Real
print("A soma do triplo do primeiro com o terceiro =", retorna2)
retorna3 = numero_Real ** 3
print ("O terceiro elevado ao cubo =", retorna3)